spring:
  application:
    name: USERSERVICE
  profiles:
    active: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: 6267496475
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
server:
  port: 8082
